### PR TITLE
Issue 44

### LINKED ISSUE #44: References: redirects
References:  The following provided "CRC Press" URLs
steer to routledge.com pages.  Should these be updated?

Original:
 [CFADLNV05]
            Cohen, H., Frey, G., Avanzi, R., Doche, C., Lange, T.,
            Nguyen, K., and F. Vercauteren, "Handbook of Elliptic and                             
            Hyperelliptic Curve Cryptography", ISBN 9781584885184,
            publisher Chapman and Hall / CRC, 2005,
            <https://www.crcpress.com/9781584885184>.
...
 [W08]      Washington, L.C., "Elliptic curves: Number theory and                                 
            cryptography", ISBN 9781420071467, publisher Chapman and
            Hall / CRC, edition 2nd, 2008,
            <https://www.crcpress.com/9781420071467>.

### PR DESCRIPTION
**Pull request by sginoza**
draft to resolve #44 

We typically try to avoid personal URLs in favor of possibly more stable and long-lived URLs.  Please confirm that these URLs are expected to be stable in the long term.

### CODE REVIEW

**Comment by chris-wood** [comment]
I'm confused -- @sginoza, this change seems to replace stable URLs with personal URLs. Was that intended?

**Comment by sginoza** [comment]
@chris-wood - Our original question was whether the links to https://www.crcpress.com should be updated since they get redirected routledge.com.   It sounds like you're in favor of one of these - which is preferable? 

FYI: I thought perhaps Armando provided to the links hosted by the authors so readers could obtain the references free of charge.  We updated the URLs but also included this followup: 

> We typically try to avoid personal URLs in favor of possibly more stable and long-lived URLs. Please confirm that these URLs are expected to be stable in the long term.

**Comment by chris-wood** [comment]
I don't know if we can expect these URLs to be stable. I would use those from the publisher. Please do what you think is best here.

**Comment by sginoza** [comment]
Leaving original URLs as provided.

**Pull request closed without merging**
